server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
      - id: getpersonas
        uri: http://localhost:9080/
        predicates:
        - Path=/getpersonas/**
      - id: addpersona
        uri: http://localhost:9081/
        predicates:
        - Path=/addpersona/**
